spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.103:3306/jpa_test?useUnicode=true&useSSL=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

